app:
  title: 'Sandbox'
system:
  debug: 'dxos:*:error'
  storage:
    persistent: true
services:
  signal:
    server: 'wss://enterprise.kube.dxos.network/dxos/signal'
  ice:
    - urls: 'turn:apollo3.kube.moon.dxos.network:3478'
      username: 'dxos'
      credential: 'dxos'
  ipfs:
    server: 'https://ipfs-enterprise.kube.dxos.network/dxos/ipfs/api'
    gateway: 'https://ipfs-enterprise.kube.dxos.network/dxos/ipfs/gateway/'
  dxns:
    server: 'wss://dxns1.kube.dxos.network/dxns/ws'
